"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

# Notes:
# 0 = black
# 1 = red
# 2 = green
# 3 = yellow
# 4 = blue
# 5 = purple
# 6 = cyan
# 7 = silver

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  type = "session"
  style = "diamond"
  background = "7"
  foreground = "0"
  background_templates = ["{{ if .SSHSession }}3{{ end }}"]
  trailing_diamond = ""
  template = "{{ .UserName }}@{{ .HostName }}"

  [[blocks.segments]]
  background = "5" # blue
  foreground = "0" # black
  trailing_diamond = ""
  style = "diamond"
  template = " {{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    style = "agnoster_short"

  [[blocks.segments]]
  background = "2" # green
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}3{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}3{{ end }}",
  "{{ if gt .Ahead 0 }}4{{ end }}",
  "{{ if gt .Behind 0 }}4{{ end }}"
]
  foreground = "0" # black
  trailing_diamond = ""
  style = "diamond"
  template = " {{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    fetch_stash_count = true
    fetch_status = true

[[blocks]]
alignment = "right"
type = "prompt"

  [[blocks.segments]]
  background = "4"
  foreground = "0" # black
  leading_diamond = " \ue0b2"
  style = "diamond"
  template = " {{ .FormattedMs }} "
  type = "executiontime"

    [blocks.segments.properties]
    style = "round"
    threshold = 2000
