theme = "vscode_adamch"

[editor]
auto-format = true
line-number = "relative"
scrolloff = 5
shell = ["zsh", "-c"]
bufferline = "multiple"
popup-border = "all"
cursorline = true
completion-timeout = 10

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Select"

[keys.normal]
X = "select_line_above"
x = "select_line_below"

[keys.normal.space]
w = ":write"
i = ":toggle lsp.display-inlay-hints"
t = ":toggle soft-wrap.enable"
# When used inside `Some(expr)` or `Ok(expr)`, replaces it with `expr`
# Very useful for writing Rust.
# x = "@mi(d<A-o><A-o>R" 
