theme = "vscode_adamch"

[editor]
auto-format = true
line-number = "relative"
scrolloff = 5
shell = ["zsh", "-c"]
bufferline = "multiple"
popup-border = "all"
cursorline = true
completion-timeout = 10

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Select"
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["version-control", "diagnostics", "workspace-diagnostics", "selections", "register", "position", "file-encoding"]


[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
X = "select_line_above"
x = "select_line_below"
ret = "goto_word"
Y = ":clipboard-yank"

[keys.select]
Y = ":clipboard-yank"

[keys.normal.space]
w = ":write"
i = ":toggle lsp.display-inlay-hints"
t = ":toggle soft-wrap.enable"
# When used inside `Some(expr)` or `Ok(expr)`, replaces it with `expr`
# Very useful for writing Rust.
x = "@mi(d<A-o><A-o>R"
# Show blame info for current line
B = ":sh git -C $(dirname $(realpath %{buffer_name})) blame -L %{cursor_line},%{cursor_line} $(realpath %{buffer_name})"
# Copy git provider url for this file and line
o = ":sh git-url-finder %{buffer_name} %{cursor_line} | pbcopy"
R = ":reset-diff-change"

